connectionTimeout = 20

verbose = false

streams {
    coracle {
        dir = "up"
        urls = [
            "wss://indexer.coracle.social/"
        ]
    }

    purplepages {
        dir = "up"
        urls = [
            "wss://purplepag.es/"
        ]
    }

    primalRelayLists {
        dir = "down"
        filter = { "kinds": [10002] }
        urls = [
            "wss://relay.primal.net/"
        ]
    }

    damusRelayLists {
        dir = "down"
        filter = { "kinds": [10002] }
        urls = [
            "wss://relay.damus.io/"
        ]
    }
}