connectionTimeout = 20

verbose = false

streams {
    riboEu {
        dir = "down"
        urls = [
            "wss://ribo.eu.nostria.app/"
        ]
    }

    riboUs {
        dir = "down"
        urls = [
            "wss://ribo.us.nostria.app/"
        ]
    }
}