connectionTimeout = 20

verbose = false

streams {
    riboEu {
        dir = "down"
        urls = [
            "wss://ribo.nostria.app/"
        ]
    }

    riboUs {
        dir = "down"
        urls = [
            "wss://rilo.nostria.app/"
        ]
    }
}